export const ApplicationErrorCode = {
  REGISTRATION_INVALID: 'REGISTRATION_INVALID',
  BANNED_CONTENT: 'BANNED_CONTENT',
  INVALID_TOURNAMENT_STATUS_TRANSITION: 'INVALID_TOURNAMENT_STATUS_TRANSITION',
  INVALID_REGISTRATION_STATUS_TRANSITION:
    'INVALID_REGISTRATION_STATUS_TRANSITION',
  EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',
  RATE_LIMITED: 'RATE_LIMITED',
} as const;

export type ApplicationErrorCode =
  (typeof ApplicationErrorCode)[keyof typeof ApplicationErrorCode];
