export const ApplicationErrorCode = {
  REGISTRATION_INVALID: 'REGISTRATION_INVALID',
  BANNED_CONTENT: 'BANNED_CONTENT',
  INVALID_TOURNAMENT_STATUS_TRANSITION: 'INVALID_TOURNAMENT_STATUS_TRANSITION',
  INVALID_REGISTRATION_STATUS_TRANSITION:
    'INVALID_REGISTRATION_STATUS_TRANSITION',
  EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',
  RATE_LIMITED: 'RATE_LIMITED',
  TOURNAMENT_NOT_FOUND: 'TOURNAMENT_NOT_FOUND',
  TOURNAMENT_NOT_MUTABLE: 'TOURNAMENT_NOT_MUTABLE',
  ROUND_NOT_MUTABLE: 'ROUND_NOT_MUTABLE',
  REGISTRATION_MUST_BE_CLOSED: 'REGISTRATION_MUST_BE_CLOSED',
  ROUND_SEQUENCE_INVALID: 'ROUND_SEQUENCE_INVALID',
  ELIMINATION_MUST_BE_TERMINAL: 'ELIMINATION_MUST_BE_TERMINAL',
  PREVIOUS_ROUND_NOT_COMPLETE: 'PREVIOUS_ROUND_NOT_COMPLETE',
  ROUND_PARTICIPANTS_NOT_READY: 'ROUND_PARTICIPANTS_NOT_READY',
  ROUND_PARTICIPANTS_INELIGIBLE: 'ROUND_PARTICIPANTS_INELIGIBLE',
  ROUND_ADVANCEMENT_SNAPSHOT_CHANGED: 'ROUND_ADVANCEMENT_SNAPSHOT_CHANGED',
  ROUND_ADVANCEMENT_ALREADY_PERSISTED: 'ROUND_ADVANCEMENT_ALREADY_PERSISTED',
  NEXT_ROUND_ALREADY_GENERATED: 'NEXT_ROUND_ALREADY_GENERATED',
  UPSTREAM_RESULT_LOCKED_BY_DOWNSTREAM_STRUCTURE:
    'UPSTREAM_RESULT_LOCKED_BY_DOWNSTREAM_STRUCTURE',
  ROUND_ADVANCEMENT_TARGET_INVALID: 'ROUND_ADVANCEMENT_TARGET_INVALID',
  ROUND_DELETE_STATE_CHANGED: 'ROUND_DELETE_STATE_CHANGED',
  ROUND_DELETE_TOURNAMENT_LOCKED: 'ROUND_DELETE_TOURNAMENT_LOCKED',
  ROUND_DELETE_NOT_LAST: 'ROUND_DELETE_NOT_LAST',
  ROUND_DELETE_HAS_DEPENDENCIES: 'ROUND_DELETE_HAS_DEPENDENCIES',
  TOURNAMENT_PARTICIPANTS_LOCKED: 'TOURNAMENT_PARTICIPANTS_LOCKED',
  ROUND_SEEDS_LOCKED: 'ROUND_SEEDS_LOCKED',
  ROUND_PREVIEW_STALE: 'ROUND_PREVIEW_STALE',
  ROUND_TIE_BREAK_REQUIRED: 'ROUND_TIE_BREAK_REQUIRED',
  ROUND_TIE_BREAK_SELECTION_INVALID: 'ROUND_TIE_BREAK_SELECTION_INVALID',
  TOURNAMENT_COMPLETION_REQUIRES_FINALIZATION:
    'TOURNAMENT_COMPLETION_REQUIRES_FINALIZATION',
  TOURNAMENT_FINALIZATION_NOT_READY: 'TOURNAMENT_FINALIZATION_NOT_READY',
  TOURNAMENT_FINALIZATION_UNSUPPORTED_FORMAT:
    'TOURNAMENT_FINALIZATION_UNSUPPORTED_FORMAT',
  TOURNAMENT_FINALIZATION_STANDINGS_INVALID:
    'TOURNAMENT_FINALIZATION_STANDINGS_INVALID',
  TOURNAMENT_CHAMPION_TIE_BREAK_REQUIRED:
    'TOURNAMENT_CHAMPION_TIE_BREAK_REQUIRED',
  TOURNAMENT_CHAMPION_SELECTION_INVALID:
    'TOURNAMENT_CHAMPION_SELECTION_INVALID',
  FINAL_STANDINGS_RESULT_LOCKED: 'FINAL_STANDINGS_RESULT_LOCKED',
  SWISS_ITERATION_NOT_COMPLETE: 'SWISS_ITERATION_NOT_COMPLETE',
  SWISS_ALL_ITERATIONS_COMPLETE: 'SWISS_ALL_ITERATIONS_COMPLETE',
  SWISS_STRUCTURE_INVALID: 'SWISS_STRUCTURE_INVALID',
  DOWNSTREAM_RESET_NOT_AVAILABLE: 'DOWNSTREAM_RESET_NOT_AVAILABLE',
  DOWNSTREAM_RESET_TOURNAMENT_LOCKED: 'DOWNSTREAM_RESET_TOURNAMENT_LOCKED',
  DOWNSTREAM_RESET_PREVIEW_STALE: 'DOWNSTREAM_RESET_PREVIEW_STALE',
} as const;

export type ApplicationErrorCode =
  (typeof ApplicationErrorCode)[keyof typeof ApplicationErrorCode];
