-- Persist deterministic winner/loser destination slots generated by bracket strategies.
CREATE TYPE "MatchSlot" AS ENUM ('A', 'B');

ALTER TABLE "matches"
  ADD COLUMN "next_match_slot" "MatchSlot",
  ADD COLUMN "loser_next_match_slot" "MatchSlot";
